"""add derived_modes to place_relations

Revision ID: 032846c058de
Revises: f1e4dec78a27
Create Date: 2026-09-10 21:47:57.964465
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '032846c058de'
down_revision: str | None = 'f1e4dec78a27'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('place_relations', sa.Column('derived_modes', sa.ARRAY(sa.Text()), server_default=sa.text("'{}'::text[]"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('place_relations', 'derived_modes')
    # ### end Alembic commands ###
