"""place and alias name uniqueness semantics

Revision ID: 217165a7a13b
Revises: 032846c058de
Create Date: 2026-09-10 21:51:57.544309
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '217165a7a13b'
down_revision: str | None = '032846c058de'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_alias_city_norm'), 'place_aliases', type_='unique')
    op.create_index('ix_alias_city_norm', 'place_aliases', ['city_id', 'alias_norm'], unique=False)
    op.create_unique_constraint('uq_alias_place_norm', 'place_aliases', ['place_id', 'alias_norm'])
    op.drop_index(op.f('uq_places_city_canonical'), table_name='places', postgresql_where="(status <> 'merged'::text)")
    op.create_index('ix_places_city_canonical', 'places', ['city_id', sa.literal_column('lower(canonical_name)')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_places_city_canonical', table_name='places')
    op.create_index(op.f('uq_places_city_canonical'), 'places', ['city_id', sa.literal_column('lower(canonical_name)')], unique=True, postgresql_where="(status <> 'merged'::text)")
    op.drop_constraint('uq_alias_place_norm', 'place_aliases', type_='unique')
    op.drop_index('ix_alias_city_norm', table_name='place_aliases')
    op.create_unique_constraint(op.f('uq_alias_city_norm'), 'place_aliases', ['city_id', 'alias_norm'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
