"""initial schema

Revision ID: f1e4dec78a27
Revises:
Create Date: 2026-09-10 12:34:42.655472

说明：
- 本环境没有 PostGIS / pgvector / 中文分词扩展（见 PROJECT_ANALYSIS.md §2），
  因此地理计算走 bbox + haversine，实体去重走「别名 + pg_trgm + 拼音 + 地理围栏 + LLM 裁判」。
- pg_trgm 是 places.display_name 模糊匹配（ix_places_name_trgm）的前置依赖，
  必须在建索引前创建，所以放在 upgrade() 的第一步。
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'f1e4dec78a27'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # pg_trgm：places.display_name 的 trigram 索引依赖它（CJK 场景下仍按字符切分可用）
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_usage_daily',
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('calls', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('cache_hits', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('units', sa.Float(), server_default=sa.text('0'), nullable=False),
    sa.Column('amount_cny', sa.Numeric(precision=10, scale=6), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('day', 'provider', 'category')
    )
    op.create_table('cities',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('name_en', sa.Text(), nullable=True),
    sa.Column('country', sa.Text(), server_default=sa.text("'CN'"), nullable=False),
    sa.Column('province', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('timezone', sa.Text(), server_default=sa.text("'Asia/Shanghai'"), nullable=False),
    sa.Column('currency', sa.Text(), server_default=sa.text("'CNY'"), nullable=False),
    sa.Column('centroid_lat', sa.Float(), nullable=True),
    sa.Column('centroid_lng', sa.Float(), nullable=True),
    sa.Column('bbox_min_lat', sa.Float(), nullable=True),
    sa.Column('bbox_max_lat', sa.Float(), nullable=True),
    sa.Column('bbox_min_lng', sa.Float(), nullable=True),
    sa.Column('bbox_max_lng', sa.Float(), nullable=True),
    sa.Column('coverage_score', sa.Numeric(precision=4, scale=3, asdecimal=False), nullable=True),
    sa.Column('status', sa.Text(), server_default=sa.text("'draft'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'seeding', 'active', 'archived')", name='ck_cities_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('cost_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.UUID(), nullable=True),
    sa.Column('trip_id', sa.UUID(), nullable=True),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('model', sa.Text(), nullable=True),
    sa.Column('operation', sa.Text(), nullable=True),
    sa.Column('units', sa.Float(), server_default=sa.text('0'), nullable=False),
    sa.Column('unit_price', sa.Float(), server_default=sa.text('0'), nullable=False),
    sa.Column('amount_cny', sa.Numeric(precision=10, scale=6), server_default=sa.text('0'), nullable=False),
    sa.Column('cache_hit', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('pricing_calibrated', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("category IN ('search','llm','map','geocode','tiles','other')", name='ck_cost_category'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cost_created', 'cost_logs', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('ix_cost_logs_request_id'), 'cost_logs', ['request_id'], unique=False)
    op.create_table('error_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.UUID(), nullable=True),
    sa.Column('level', sa.Text(), nullable=False),
    sa.Column('component', sa.Text(), nullable=False),
    sa.Column('code', sa.Text(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("level IN ('debug','info','warning','error','critical')", name='ck_error_level'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_error_created', 'error_logs', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('ix_error_logs_request_id'), 'error_logs', ['request_id'], unique=False)
    op.create_table('llm_cache',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('cache_key', sa.Text(), nullable=False),
    sa.Column('tier', sa.Text(), nullable=False),
    sa.Column('model', sa.Text(), nullable=False),
    sa.Column('prompt_hash', sa.Text(), nullable=False),
    sa.Column('task', sa.Text(), nullable=False),
    sa.Column('response', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tokens_in', sa.Integer(), nullable=True),
    sa.Column('tokens_out', sa.Integer(), nullable=True),
    sa.Column('tokens_cached', sa.Integer(), nullable=True),
    sa.Column('cost_cny', sa.Numeric(precision=10, scale=6), server_default=sa.text('0'), nullable=False),
    sa.Column('hit_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_hit_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("tier IN ('fast','strong')", name='ck_llm_cache_tier'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cache_key')
    )
    op.create_index('ix_llm_cache_exp', 'llm_cache', ['expires_at'], unique=False)
    op.create_index('ix_llm_cache_task', 'llm_cache', ['task'], unique=False)
    op.create_table('rate_limit_counters',
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('key', 'window_start')
    )
    op.create_table('search_cache',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('cache_key', sa.Text(), nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('locale', sa.Text(), server_default=sa.text("'zh-CN'"), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('extracted', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cost_cny', sa.Numeric(precision=10, scale=6), server_default=sa.text('0'), nullable=False),
    sa.Column('hit_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_hit_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cache_key')
    )
    op.create_index('ix_search_cache_exp', 'search_cache', ['expires_at'], unique=False)
    op.create_table('travel_sources',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('source_type', sa.Text(), nullable=False),
    sa.Column('source_name', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('url_hash', sa.Text(), nullable=True),
    sa.Column('domain', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('language', sa.Text(), server_default=sa.text("'zh'"), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('robots_allowed', sa.Boolean(), nullable=True),
    sa.Column('content_hash', sa.Text(), nullable=True),
    sa.Column('extracted_facts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('credibility_score', sa.Float(), server_default=sa.text('0.5'), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source_type IN ('official','gov','tourism_bureau','ota','media','blog','ugc','map_api','search_api','llm_inference','manual','editorial')", name='ck_source_type'),
    sa.CheckConstraint('credibility_score >= 0 AND credibility_score <= 1', name='ck_source_credibility'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sources_cred', 'travel_sources', [sa.literal_column('credibility_score DESC')], unique=False)
    op.create_index('uq_sources_url_hash', 'travel_sources', ['url_hash'], unique=True, postgresql_where=sa.text('url_hash IS NOT NULL'))
    op.create_table('trip_requests',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('raw_input', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('free_text_len', sa.Integer(), nullable=True),
    sa.Column('free_text_masked', sa.Text(), nullable=True),
    sa.Column('intent', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('constraints', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('parse_source', sa.Text(), nullable=True),
    sa.Column('params_hash', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('error_code', sa.Text(), nullable=True),
    sa.Column('ip_hash', sa.Text(), nullable=True),
    sa.Column('user_agent_hash', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('elapsed_ms', sa.Integer(), nullable=True),
    sa.CheckConstraint("parse_source IS NULL OR parse_source IN ('rule','llm','cache','hybrid')", name='ck_trip_requests_parse_source'),
    sa.CheckConstraint("status IN ('pending','running','completed','failed','cancelled','degraded')", name='ck_trip_requests_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_req_params_hash', 'trip_requests', ['params_hash', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('ix_req_session', 'trip_requests', ['session_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('kb_versions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('version', sa.Text(), nullable=False),
    sa.Column('city_id', sa.UUID(), nullable=True),
    sa.Column('place_count', sa.Integer(), nullable=True),
    sa.Column('route_count', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('quality_report', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version')
    )
    op.create_table('places',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('city_id', sa.UUID(), nullable=False),
    sa.Column('canonical_name', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('name_en', sa.Text(), nullable=True),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('subcategory', sa.Text(), nullable=True),
    sa.Column('district', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('geohash', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('recommended_duration_min', sa.Integer(), nullable=True),
    sa.Column('opening_hours', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('opening_hours_raw', sa.Text(), nullable=True),
    sa.Column('price_min', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_max', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_note', sa.Text(), nullable=True),
    sa.Column('best_time', sa.ARRAY(sa.Text()), server_default=sa.text("'{}'::text[]"), nullable=False),
    sa.Column('best_season', sa.ARRAY(sa.Text()), server_default=sa.text("'{}'::text[]"), nullable=False),
    sa.Column('indoor', sa.Boolean(), nullable=True),
    sa.Column('reservation_required', sa.Boolean(), nullable=True),
    sa.Column('crowd_level', sa.Text(), nullable=True),
    sa.Column('popularity_score', sa.Numeric(precision=4, scale=3, asdecimal=False), nullable=True),
    sa.Column('photo_score', sa.Numeric(precision=4, scale=3, asdecimal=False), nullable=True),
    sa.Column('food_score', sa.Numeric(precision=4, scale=3, asdecimal=False), nullable=True),
    sa.Column('culture_score', sa.Numeric(precision=4, scale=3, asdecimal=False), nullable=True),
    sa.Column('night_view_score', sa.Numeric(precision=4, scale=3, asdecimal=False), nullable=True),
    sa.Column('family_score', sa.Numeric(precision=4, scale=3, asdecimal=False), nullable=True),
    sa.Column('couple_score', sa.Numeric(precision=4, scale=3, asdecimal=False), nullable=True),
    sa.Column('walkability_score', sa.Numeric(precision=4, scale=3, asdecimal=False), nullable=True),
    sa.Column('rainy_day_score', sa.Numeric(precision=4, scale=3, asdecimal=False), nullable=True),
    sa.Column('quiet_score', sa.Numeric(precision=4, scale=3, asdecimal=False), nullable=True),
    sa.Column('seat_score', sa.Numeric(precision=4, scale=3, asdecimal=False), nullable=True),
    sa.Column('tags', sa.ARRAY(sa.Text()), server_default=sa.text("'{}'::text[]"), nullable=False),
    sa.Column('primary_source_id', sa.UUID(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('source_name', sa.Text(), nullable=True),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verification_status', sa.Text(), server_default=sa.text("'unknown'"), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3, asdecimal=False), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('unknown_fields', sa.ARRAY(sa.Text()), server_default=sa.text("'{}'::text[]"), nullable=False),
    sa.Column('data_quality_flags', sa.ARRAY(sa.Text()), server_default=sa.text("'{}'::text[]"), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'active'"), nullable=False),
    sa.Column('merged_into_place_id', sa.UUID(), nullable=True),
    sa.Column('external_source', sa.Text(), nullable=True),
    sa.Column('external_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("category IN ('attraction', 'district', 'food', 'cafe', 'museum', 'historic', 'citywalk', 'photo', 'nightview', 'family', 'shopping', 'nature', 'transport_hub')", name='ck_places_category'),
    sa.CheckConstraint("status IN ('active', 'candidate', 'merged', 'archived')", name='ck_places_status'),
    sa.CheckConstraint("verification_status <> 'verified' OR source_url IS NOT NULL", name='ck_places_verified_needs_source'),
    sa.CheckConstraint("verification_status IN ('verified', 'probable', 'unknown', 'stale', 'conflicting')", name='ck_places_verification'),
    sa.CheckConstraint('latitude <> 0 AND longitude <> 0', name='ck_places_coord_not_zero'),
    sa.CheckConstraint('merged_into_place_id IS NULL OR merged_into_place_id <> id', name='ck_places_merge_not_self'),
    sa.CheckConstraint('price_min IS NULL OR price_max IS NULL OR price_min <= price_max', name='ck_places_price_order'),
    sa.CheckConstraint('recommended_duration_min IS NULL OR (recommended_duration_min >= 10 AND recommended_duration_min <= 720)', name='ck_places_duration_range'),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['merged_into_place_id'], ['places.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['primary_source_id'], ['travel_sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_places_bbox', 'places', ['city_id', 'latitude', 'longitude'], unique=False)
    op.create_index('ix_places_city_status_cat', 'places', ['city_id', 'status', 'category'], unique=False)
    op.create_index('ix_places_external', 'places', ['external_source', 'external_id'], unique=False)
    op.create_index('ix_places_geohash', 'places', ['geohash'], unique=False)
    op.create_index('ix_places_name_trgm', 'places', ['display_name'], unique=False, postgresql_using='gin', postgresql_ops={'display_name': 'gin_trgm_ops'})
    op.create_index('ix_places_popularity', 'places', ['city_id', sa.literal_column('popularity_score DESC NULLS LAST')], unique=False)
    op.create_index('ix_places_tags', 'places', ['tags'], unique=False, postgresql_using='gin')
    op.create_index('uq_places_city_canonical', 'places', ['city_id', sa.literal_column('lower(canonical_name)')], unique=True, postgresql_where=sa.text("status <> 'merged'"))
    op.create_table('routes',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('city_id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('route_type', sa.Text(), nullable=False),
    sa.Column('archetype_hint', sa.Text(), nullable=True),
    sa.Column('difficulty', sa.Text(), nullable=True),
    sa.Column('pace', sa.Text(), nullable=True),
    sa.Column('duration_min', sa.Integer(), nullable=True),
    sa.Column('walking_distance_m', sa.Integer(), nullable=True),
    sa.Column('estimated_transport_time_min', sa.Integer(), nullable=True),
    sa.Column('estimated_budget_min', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('estimated_budget_max', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('recommended_start_time', sa.Time(), nullable=True),
    sa.Column('recommended_end_time', sa.Time(), nullable=True),
    sa.Column('best_for', sa.ARRAY(sa.Text()), server_default=sa.text("'{}'::text[]"), nullable=False),
    sa.Column('score', sa.Numeric(precision=4, scale=3, asdecimal=False), nullable=True),
    sa.Column('is_template', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('usage_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('source_name', sa.Text(), nullable=True),
    sa.Column('verification_status', sa.Text(), server_default=sa.text("'unknown'"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("archetype_hint IS NULL OR archetype_hint IN ('relaxed','classic','themed')", name='ck_routes_archetype'),
    sa.CheckConstraint("difficulty IS NULL OR difficulty IN ('easy','moderate','hard')", name='ck_routes_difficulty'),
    sa.CheckConstraint("pace IS NULL OR pace IN ('relaxed','balanced','packed')", name='ck_routes_pace'),
    sa.CheckConstraint("route_type IN ('classic', 'food', 'photo', 'culture', 'night_view', 'family', 'couple', 'citywalk', 'relax', 'nature', 'shopping', 'museum')", name='ck_routes_type'),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('city_id', 'slug', name='uq_routes_city_slug')
    )
    op.create_index('ix_routes_city_type', 'routes', ['city_id', 'route_type'], unique=False)
    op.create_table('trips',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('city_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('intent_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('days', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('route_count', sa.Integer(), nullable=False),
    sa.Column('share_slug', sa.Text(), nullable=True),
    sa.Column('is_public', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('shared_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('generation_ms', sa.Integer(), nullable=True),
    sa.Column('total_cost_cny', sa.Numeric(precision=10, scale=6), server_default=sa.text('0'), nullable=False),
    sa.Column('degraded_modes', sa.ARRAY(sa.Text()), server_default=sa.text("'{}'::text[]"), nullable=False),
    sa.Column('revision_no', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('parent_trip_id', sa.UUID(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_trip_id'], ['trips.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['request_id'], ['trip_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('share_slug')
    )
    op.create_index('ix_trips_session', 'trips', ['session_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('ix_trips_share', 'trips', ['share_slug'], unique=False, postgresql_where=sa.text('is_public = true'))
    op.create_table('feedback',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=True),
    sa.Column('place_id', sa.UUID(), nullable=True),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('contact', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), server_default=sa.text("'open'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("category IN ('wrong_hours','wrong_price','closed','bad_route','wrong_coord','other')", name='ck_feedback_category'),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_feedback_created', 'feedback', [sa.literal_column('created_at DESC')], unique=False)
    op.create_table('merge_logs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('keep_place_id', sa.UUID(), nullable=False),
    sa.Column('drop_place_id', sa.UUID(), nullable=False),
    sa.Column('match_level', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3, asdecimal=False), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reverted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['drop_place_id'], ['places.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['keep_place_id'], ['places.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_merge_keep', 'merge_logs', ['keep_place_id'], unique=False)
    op.create_table('place_aliases',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('place_id', sa.UUID(), nullable=False),
    sa.Column('city_id', sa.UUID(), nullable=False),
    sa.Column('alias', sa.Text(), nullable=False),
    sa.Column('alias_norm', sa.Text(), nullable=False),
    sa.Column('alias_type', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3, asdecimal=False), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("alias_type IN ('zh_variant','en','abbr','historic','common_misspell','poi_name','search_term')", name='ck_alias_type'),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('city_id', 'alias_norm', name='uq_alias_city_norm')
    )
    op.create_index('ix_alias_place', 'place_aliases', ['place_id'], unique=False)
    op.create_table('place_external_ids',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('place_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('external_id', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'external_id', name='uq_external_provider_id')
    )
    op.create_index('ix_external_place', 'place_external_ids', ['place_id'], unique=False)
    op.create_table('place_relations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('city_id', sa.UUID(), nullable=False),
    sa.Column('place_a_id', sa.UUID(), nullable=False),
    sa.Column('place_b_id', sa.UUID(), nullable=False),
    sa.Column('distance_m', sa.Integer(), nullable=True),
    sa.Column('walking_time_min', sa.Integer(), nullable=True),
    sa.Column('driving_time_min', sa.Integer(), nullable=True),
    sa.Column('transit_time_min', sa.Integer(), nullable=True),
    sa.Column('cycling_time_min', sa.Integer(), nullable=True),
    sa.Column('relationship_score', sa.Numeric(precision=4, scale=3, asdecimal=False), nullable=True),
    sa.Column('recommended_transport', sa.Text(), nullable=True),
    sa.Column('recommended_together', sa.Boolean(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('geometry_ref', sa.Text(), nullable=True),
    sa.Column('data_source', sa.Text(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("data_source IN ('amap','osrm','estimated','manual')", name='ck_relation_source'),
    sa.CheckConstraint('place_a_id < place_b_id', name='ck_relation_order'),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['place_a_id'], ['places.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['place_b_id'], ['places.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('place_a_id', 'place_b_id', name='uq_relation_pair')
    )
    op.create_index('ix_rel_a', 'place_relations', ['place_a_id'], unique=False)
    op.create_index('ix_rel_b', 'place_relations', ['place_b_id'], unique=False)
    op.create_index('ix_rel_expires', 'place_relations', ['expires_at'], unique=False)
    op.create_table('place_sources',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('place_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('field_scope', sa.ARRAY(sa.Text()), server_default=sa.text("'{}'::text[]"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['travel_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('place_id', 'source_id', name='uq_place_source')
    )
    op.create_table('plan_cache',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('params_hash', sa.Text(), nullable=False),
    sa.Column('kb_version', sa.Text(), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('hit_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('params_hash', 'kb_version', name='uq_plan_cache_key')
    )
    op.create_table('route_places',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('route_id', sa.UUID(), nullable=False),
    sa.Column('place_id', sa.UUID(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('stay_min', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('transport_to_next', sa.Text(), nullable=True),
    sa.Column('transport_to_next_min', sa.Integer(), nullable=True),
    sa.Column('distance_to_next_m', sa.Integer(), nullable=True),
    sa.CheckConstraint("transport_to_next IS NULL OR transport_to_next IN ('walk','metro','bus','taxi','bike','ferry')", name='ck_route_places_transport'),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('route_id', 'seq', name='uq_route_places_seq')
    )
    op.create_index('ix_route_places_place', 'route_places', ['place_id'], unique=False)
    op.create_table('trip_revisions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('parent_revision_id', sa.UUID(), nullable=True),
    sa.Column('instruction', sa.Text(), nullable=True),
    sa.Column('parsed_delta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('result_trip_id', sa.UUID(), nullable=True),
    sa.Column('diff_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('parse_source', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_revision_id'], ['trip_revisions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['result_trip_id'], ['trips.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_revisions_trip', 'trip_revisions', ['trip_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('trip_routes',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('archetype', sa.Text(), nullable=False),
    sa.Column('theme', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('one_liner', sa.Text(), nullable=True),
    sa.Column('total_duration_min', sa.Integer(), nullable=False),
    sa.Column('total_distance_m', sa.Integer(), nullable=True),
    sa.Column('walking_distance_m', sa.Integer(), nullable=True),
    sa.Column('transit_time_min', sa.Integer(), nullable=True),
    sa.Column('transit_distance_m', sa.Integer(), nullable=True),
    sa.Column('budget_min', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('budget_max', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('budget_scope', sa.Text(), server_default=sa.text("'per_person'"), nullable=True),
    sa.Column('place_count', sa.Integer(), nullable=False),
    sa.Column('recommend_score', sa.Float(), nullable=False),
    sa.Column('score_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('best_for', sa.ARRAY(sa.Text()), server_default=sa.text("'{}'::text[]"), nullable=False),
    sa.Column('highlights', sa.ARRAY(sa.Text()), server_default=sa.text("'{}'::text[]"), nullable=False),
    sa.Column('pros', sa.ARRAY(sa.Text()), server_default=sa.text("'{}'::text[]"), nullable=False),
    sa.Column('cons', sa.ARRAY(sa.Text()), server_default=sa.text("'{}'::text[]"), nullable=False),
    sa.Column('recommendation_reason', sa.Text(), nullable=True),
    sa.Column('feasibility_report', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('polyline', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('route_source', sa.Text(), nullable=True),
    sa.Column('template_route_id', sa.UUID(), nullable=True),
    sa.Column('is_selected', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("archetype IN ('relaxed','classic','themed')", name='ck_trip_routes_archetype'),
    sa.CheckConstraint("label IN ('A','B','C','D')", name='ck_trip_routes_label'),
    sa.CheckConstraint('recommend_score >= 0 AND recommend_score <= 1', name='ck_trip_routes_score'),
    sa.ForeignKeyConstraint(['template_route_id'], ['routes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_trip_routes_trip', 'trip_routes', ['trip_id', 'sort_order'], unique=False)
    op.create_table('trip_route_stops',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('trip_route_id', sa.UUID(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('place_id', sa.UUID(), nullable=False),
    sa.Column('place_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('arrive_time', sa.Time(), nullable=False),
    sa.Column('depart_time', sa.Time(), nullable=False),
    sa.Column('stay_min', sa.Integer(), nullable=False),
    sa.Column('transport_mode', sa.Text(), nullable=True),
    sa.Column('transport_min', sa.Integer(), nullable=True),
    sa.Column('transport_distance_m', sa.Integer(), nullable=True),
    sa.Column('transport_source', sa.Text(), nullable=True),
    sa.Column('why_recommended', sa.Text(), nullable=True),
    sa.Column('tips', sa.Text(), nullable=True),
    sa.Column('source_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('warnings', sa.ARRAY(sa.Text()), server_default=sa.text("'{}'::text[]"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("transport_mode IS NULL OR transport_mode IN ('walk','metro','bus','taxi','bike','ferry','none')", name='ck_stops_transport_mode'),
    sa.CheckConstraint("transport_source IS NULL OR transport_source IN ('amap','osrm','estimated','manual')", name='ck_stops_transport_source'),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['trip_route_id'], ['trip_routes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trip_route_id', 'seq', name='uq_trip_route_stops_seq')
    )
    op.create_index('ix_stops_route', 'trip_route_stops', ['trip_route_id', 'seq'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_stops_route', table_name='trip_route_stops')
    op.drop_table('trip_route_stops')
    op.drop_index('ix_trip_routes_trip', table_name='trip_routes')
    op.drop_table('trip_routes')
    op.drop_index('ix_revisions_trip', table_name='trip_revisions')
    op.drop_table('trip_revisions')
    op.drop_index('ix_route_places_place', table_name='route_places')
    op.drop_table('route_places')
    op.drop_table('plan_cache')
    op.drop_table('place_sources')
    op.drop_index('ix_rel_expires', table_name='place_relations')
    op.drop_index('ix_rel_b', table_name='place_relations')
    op.drop_index('ix_rel_a', table_name='place_relations')
    op.drop_table('place_relations')
    op.drop_index('ix_external_place', table_name='place_external_ids')
    op.drop_table('place_external_ids')
    op.drop_index('ix_alias_place', table_name='place_aliases')
    op.drop_table('place_aliases')
    op.drop_index('ix_merge_keep', table_name='merge_logs')
    op.drop_table('merge_logs')
    op.drop_index('ix_feedback_created', table_name='feedback')
    op.drop_table('feedback')
    op.drop_index('ix_trips_share', table_name='trips', postgresql_where=sa.text('is_public = true'))
    op.drop_index('ix_trips_session', table_name='trips')
    op.drop_table('trips')
    op.drop_index('ix_routes_city_type', table_name='routes')
    op.drop_table('routes')
    op.drop_index('uq_places_city_canonical', table_name='places', postgresql_where=sa.text("status <> 'merged'"))
    op.drop_index('ix_places_tags', table_name='places', postgresql_using='gin')
    op.drop_index('ix_places_popularity', table_name='places')
    op.drop_index('ix_places_name_trgm', table_name='places', postgresql_using='gin')
    op.drop_index('ix_places_geohash', table_name='places')
    op.drop_index('ix_places_external', table_name='places')
    op.drop_index('ix_places_city_status_cat', table_name='places')
    op.drop_index('ix_places_bbox', table_name='places')
    op.drop_table('places')
    op.drop_table('kb_versions')
    op.drop_index('ix_req_session', table_name='trip_requests')
    op.drop_index('ix_req_params_hash', table_name='trip_requests')
    op.drop_table('trip_requests')
    op.drop_index('uq_sources_url_hash', table_name='travel_sources', postgresql_where=sa.text('url_hash IS NOT NULL'))
    op.drop_index('ix_sources_cred', table_name='travel_sources')
    op.drop_table('travel_sources')
    op.drop_index('ix_search_cache_exp', table_name='search_cache')
    op.drop_table('search_cache')
    op.drop_table('rate_limit_counters')
    op.drop_index('ix_llm_cache_task', table_name='llm_cache')
    op.drop_index('ix_llm_cache_exp', table_name='llm_cache')
    op.drop_table('llm_cache')
    op.drop_index(op.f('ix_error_logs_request_id'), table_name='error_logs')
    op.drop_index('ix_error_created', table_name='error_logs')
    op.drop_table('error_logs')
    op.drop_index(op.f('ix_cost_logs_request_id'), table_name='cost_logs')
    op.drop_index('ix_cost_created', table_name='cost_logs')
    op.drop_table('cost_logs')
    op.drop_table('cities')
    op.drop_table('api_usage_daily')
    # ### end Alembic commands ###
